services:
  ai-server:
    build:
      context: ./ai_server
    ports:
      - 5000:5000
    env_file:
      - ./ai_server/.env
    networks:
      - internal

  api-server:
    build:
      context: ./server
    ports:
      - 5108:5108
    env_file:
      - ./server/.env
    networks:
      - internal

  client:
    build:
      context: ./website
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    networks:
      - internal

  proxy:
    build:
      context: ./proxy
    ports:
      - 81:81
    restart: always
    networks:
      - internal
    depends_on:
      - ai-server
      - api-server
      - client

networks:
  internal: