services:
  server:
    build:
      context: ./ai_server
    ports:
      - 5000:5000
    env_file:
      - ./ai_server/.env
    networks:
      - internal
  proxy:
    build:
      context: ./proxy
    ports:
      - 81:81
    restart: always
    networks:
      - internal
    depends_on:
      - server

networks:
  internal: