services:
  ai-server:
    build:
      context: ./ai_server
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./ai_server:/app
    env_file:
      - ./ai_server/.env
    networks:
      - internal
  # api-server:
  #   build:
  #     context: ./server
  #   ports:
  #     - 8090:8090
  #   networks:
  #     - internal
  client:
    build:
      context: ./website
      dockerfile: dev.Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5173:5173
    volumes:
      - ./website/src:/usr/src/app/src
    networks:
      - internal

  proxy:
    build:
      context: ./proxy
    ports:
      - 81:81
    restart: always
    networks:
      - internal
    depends_on:
      # - ai-server
      # - api-server
      - client

networks:
  internal: